package com.cardrestricted.persistence;

public enum JournalEventType
{
    COLLECTION_CREATED,
    POINTS_AWARDED,
    NONCOMBAT_XP_PROCESSED,
    PACK_PURCHASED,
    PACK_REVEAL_ADVANCED,
    NEXUS_EXCHANGE,
    NEXUS_CACHE_PURCHASED,
    PROGRESSION_REWARD_GRANTED,
    CATALOGUE_MIGRATED,
    ACHIEVEMENTS_RECONCILED,
    STATE_UPDATED
}
